require("./main")
require("./hook")
require("./nested-properties")
require("./undefined-properties")
require("./keys")
require("./thunk")
require("./style")
require("./attributes")

require("../vdom/test/")
require("../vtree/test/")
require("../virtual-hyperscript/test/")
require("../vnode/test/")
